parameters:
#    david_web.example.class: David\WebBundle\Example

services:
#    david_web.example:
#        class: %david_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
